import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <!DOCTYPE html>
    <html>
    
    <head>
        <!-- Basic -->
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <!-- Mobile Metas -->
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <!-- Site Metas -->
        <link rel="icon" href="images/favicon.png" type="image/gif" />
        <meta name="keywords" content="" />
        <meta name="description" content="" />
        <meta name="author" content="" />
    
        <title>Bostorek</title>
    
        <!-- bootstrap core css -->
        <link rel="stylesheet" type="text/css" href="css/bootstrap.css" />
        <!-- font awesome style -->
        <link href="css/font-awesome.min.css" rel="stylesheet" />
    
        <!-- Custom styles for this template -->
        <link href="css/style.css" rel="stylesheet" />
        <!-- responsive style -->
        <link href="css/responsive.css" rel="stylesheet" />
    
    </head>
    
    <body>
    
        <!-- Navigation Section -->
        <header class="header_section">
            <div class="container-fluid">
                <nav class="navbar navbar-expand-lg custom_nav-container">
                    <a class="navbar-brand" href="index.html">
                        <span>Bostorek</span>
                    </a>
    
                    <button class="navbar-toggler" type="button" data-toggle="collapse"
                        data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                        aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
    
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav ml-auto">
                            <li class="nav-item">
                                <a class="nav-link" href="index.html">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="about.html">About</a>
                            </li>
                            <li class="nav-item active">
                                <a class="nav-link" href="books.html">Books <span class="sr-only">(current)</span></a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="categories.html">Categories</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="blog.html">Blog</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="contact.html">Contact Us</a>
                            </li>
                        </ul>
                        <form class="form-inline my-2 my-lg-0">
                            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                            <button class="btn btn-outline-light my-2 my-sm-0" type="submit">Search</button>
                        </form>
                    </div>
                </nav>
            </div>
        </header>
        <!-- End Navigation Section -->
    
        <!-- Books Section -->
        <section class="books_section layout_padding">
            <div class="container">
                <div class="heading_container heading_center">
                    <h2>Our Books</h2>
                    <p>Explore our collection of books available at Bostorek Bookstore.</p>
                </div>
                <div class="row my-5">
                    <div class="col-md-3">
                        <div class="card">
                            <img src="https://bizflyportal.mediacdn.vn/thumb_wm/1000,100/bizflyportal/images/htm16157919239459.jpg"
                                class="card-img-top" alt="Book Cover">
                            <div class="card-body">
                                <h5 class="card-title">Book Title</h5>
                                <p class="card-text">Author: John Doe</p>
                                <p class="card-text">Category: Fiction</p>
                                <p class="card-text">Price: $20.00</p>
                                <a href="#" class="btn btn-primary">Buy Now</a>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="card">
                            <img src="https://bizflyportal.mediacdn.vn/thumb_wm/1000,100/bizflyportal/images/htm16157919239459.jpg"
                                class="card-img-top" alt="Book Cover">
                            <div class="card-body">
                                <h5 class="card-title">Book Title</h5>
                                <p class="card-text">Author: John Doe</p>
                                <p class="card-text">Category: Fiction</p>
                                <p class="card-text">Price: $20.00</p>
                                <a href="#" class="btn btn-primary">Buy Now</a>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="card">
                            <img src="https://bizflyportal.mediacdn.vn/thumb_wm/1000,100/bizflyportal/images/htm16157919239459.jpg"
                                class="card-img-top" alt="Book Cover">
                            <div class="card-body">
                                <h5 class="card-title">Book Title</h5>
                                <p class="card-text">Author: John Doe</p>
                                <p class="card-text">Category: Fiction</p>
                                <p class="card-text">Price: $20.00</p>
                                <a href="#" class="btn btn-primary">Buy Now</a>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="card">
                            <img src="https://bizflyportal.mediacdn.vn/thumb_wm/1000,100/bizflyportal/images/htm16157919239459.jpg"
                                class="card-img-top" alt="Book Cover">
                            <div class="card-body">
                                <h5 class="card-title">Another Book Title</h5>
                                <p class="card-text">Author: Jane Smith</p>
                                <p class="card-text">Category: Mystery</p>
                                <p class="card-text">Price: $18.50</p>
                                <a href="#" class="btn btn-primary">Buy Now</a>
                            </div>
                        </div>
                    </div>
                    <!-- Add more books as needed -->
                </div>
            </div>
        </section>
    
        <section class="blog_section layout_padding">
            <div class="container">
                <div class="heading_container heading_center">
                    <h2>
                        From Our Blog
                    </h2>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="box">
                            <div class="img-box">
                                <img src="images/b1.jpg" alt="">
                                <h4 class="blog_date">
                                    <span>
                                        19 January 2021
                                    </span>
                                </h4>
                            </div>
                            <div class="detail-box">
                                <h5>
                                    Eius, dolor? Vel velit sed doloremque
                                </h5>
                                <p>
                                    Incidunt magni explicabo ullam ipsa quo consequuntur eveniet illo? Aspernatur nam
                                    dolorem a neque? Esse eaque dolores hic debitis cupiditate, ad beatae voluptatem numquam
                                    dignissimos ab porro
                                </p>
                                <a href="">
                                    Read More
                                </a>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="box">
                            <div class="img-box">
                                <img src="images/b2.jpg" alt="">
                                <h4 class="blog_date">
                                    <span>
                                        19 January 2021
                                    </span>
                                </h4>
                            </div>
                            <div class="detail-box">
                                <h5>
                                    Minus aliquid alias porro iure fuga
                                </h5>
                                <p>
                                    Officiis veritatis id illo eligendi repellat facilis animi adipisci praesentium. Tempore
                                    ab provident porro illo ex obcaecati deleniti enim sequi voluptas at. Harum veniam eos
                                    nisi distinctio! Porro, reiciendis eius.
                                </p>
                                <a href="">
                                    Read More
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    
        <!-- end blog section -->
    
        <!-- contact section -->
    
        <section class="contact_section layout_padding">
            <div class="container">
                <div class="row">
                    <div class="col-md-6 ">
                        <div class="heading_container ">
                            <h2 class="">
                                Contact Us
                            </h2>
                        </div>
                        <form action="#">
                            <div>
                                <input type="text" placeholder="Name" />
                            </div>
                            <div>
                                <input type="email" placeholder="Email" />
                            </div>
                            <div>
                                <input type="text" placeholder="Pone Number" />
                            </div>
                            <div>
                                <input type="text" class="message-box" placeholder="Message" />
                            </div>
                            <div class="btn-box">
                                <button>
                                    SEND
                                </button>
                            </div>
                        </form>
                    </div>
                    <div class="col-md-6">
                        <div class="img-box">
                            <img src="images/contact-img.png" alt="">
                        </div>
                    </div>
                </div>
            </div>
        </section>
    
        <!-- end contact section -->
    
        <!-- info section -->
    
        <section class="info_section layout_padding2">
            <div class="container">
                <div class="row">
                    <div class="col-md-6 col-lg-3 info-col">
                        <div class="info_detail">
                            <h4>
                                About Us
                            </h4>
                            <p>
                                Vitae aut explicabo fugit facere alias distinctio, exem commodi mollitia minusem dignissimos
                                atque asperiores incidunt vel voluptate iste
                            </p>
                            <div class="info_social">
                                <a href="">
                                    <i class="fa fa-facebook" aria-hidden="true"></i>
                                </a>
                                <a href="">
                                    <i class="fa fa-twitter" aria-hidden="true"></i>
                                </a>
                                <a href="">
                                    <i class="fa fa-linkedin" aria-hidden="true"></i>
                                </a>
                                <a href="">
                                    <i class="fa fa-instagram" aria-hidden="true"></i>
                                </a>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6 col-lg-3 info-col">
                        <div class="info_contact">
                            <h4>
                                Address
                            </h4>
                            <div class="contact_link_box">
                                <a href="">
                                    <i class="fa fa-map-marker" aria-hidden="true"></i>
                                    <span>
                                        Location
                                    </span>
                                </a>
                                <a href="">
                                    <i class="fa fa-phone" aria-hidden="true"></i>
                                    <span>
                                        Call +01 1234567890
                                    </span>
                                </a>
                                <a href="">
                                    <i class="fa fa-envelope" aria-hidden="true"></i>
                                    <span>
                                        demo@gmail.com
                                    </span>
                                </a>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6 col-lg-3 info-col">
                        <div class="info_contact">
                            <h4>
                                Newsletter
                            </h4>
                            <form action="#">
                                <input type="text" placeholder="Enter email" />
                                <button type="submit">
                                    Subscribe
                                </button>
                            </form>
                        </div>
                    </div>
                    <div class="col-md-6 col-lg-3 info-col">
                        <div class="map_container">
                            <div class="map">
                                <div id="googleMap"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    
        <!-- end info section -->
    
        <!-- footer section -->
        <footer class="footer_section">
            <div class="container">
                <p>
                    &copy; <span id="displayYear"></span> All Rights Reserved By
                    <a href="https://html.design/">Free Html Templates</a>
                </p>
            </div>
        </footer>
        <!-- footer section -->
    
        <!-- jQery -->
        <script src="js/jquery-3.4.1.min.js"></script>
        <!-- bootstrap js -->
        <script src="js/bootstrap.js"></script>
        <!-- custom js -->
        <script src="js/custom.js"></script>
        <!-- Google Map -->
        <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCh39n5U-4IoWpsVGUHWdqB6puEkhRLdmI&callback=myMap">
        </script>
        <!-- End Google Map -->
    
    </body>
    
    </html>
  );
}
